---
- name: git clone netgroup/rose-srv6-tutorial
  git:
    repo: https://github.com/netgroup/rose-srv6-tutorial
    dest: "{{ rose_path }}"
    force: yes
  changed_when: false

- name: Install python dependencies
  pip:
    requirements: "{{ rose_path }}"/requirements.txt
