---
- name: git clone netgroup/rose-srv6-tutorial
  git:
    repo: https://github.com/netgroup/rose-srv6-tutorial
    dest: "{{ rose_path }}"
    force: yes
  changed_when: false

# mininetがroot権限での実行を必要とするため，rootユーザがパッケージを見つけれないといけない
# 何か他に方法がある気がしなくもないがひとまずはスクリプトファイルがある箇所にパッケージをインストールすることで対処
- name: Install python dependencies
  pip:
    requirements: "{{ rose_path }}/requirements.txt"
    extra_args: "-t {{ item }}"
  loop:
    - "{{ rose_path }}/nets/8routers-isis-ipv6/"
    - "{{ rose_path }}/nets/8r-1c-in-band-isis/"
